# Site settings
title: "Java for TypeScript Developers: Migration Guide"
url: "https://jam-mar.github.io"
baseurl: "/Java_for_TypeScript_Developers"
description: >-
  A comprehensive guide for TypeScript and Node.js developers 
  transitioning to Java, Spring, Hibernate, and the enterprise ecosystem.

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

# --- THIS BLOCK IS REQUIRED FOR JEKYLL'S CORE ---
# It tells Jekyll to process the _modules folder.
collections:
  modules:
    output: true
# -----------------------------------------------

# Theme settings for Just the Docs
# This tells the theme to build navigation for the 'modules' collection.
just_the_docs:
  collections:
    modules:
      name: Course Modules
color_scheme: engage

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - unused/
